#! /bin/sh

T="${label:="${LABEL:="$1"}"}"

if [ -z "$T" ] ; then
	echo '$label and $1 is not set' 1>&2
	exit 1
fi

B_SYSTEM_NAME="`/bin/uname -s`"
if [ "${B_SYSTEM_NAME#MINGW}" != "$B_SYSTEM_NAME" -a "${T%-cygwin}" != "$T" ] ; then
	exec 'C:/cygwin64/bin/sh.exe' -lxe "$0"
	exit 1
elif [ "${B_SYSTEM_NAME#CYGWIN}" != "$B_SYSTEM_NAME" -a "${T%-msys}" != "$T" ] ; then
	exec 'E:/software/_dev_/Git/bin/sh.exe' -lxe "$0"
	exit 1
fi
