#! /bin/bash

NDK=/usr/local/lib/android-ndk

if [ "$WORKSPACE" ] && [ -d "$WORKSPACE" ] ; then
	ON_BUILDBOT=1
else
	ON_BUILDBOT=
	WORKSPACE="$PWD"
fi

all() {
	a="$1"
	shift
	b="$1"
	shift
	for o ; do
		echo "--$a-$b=$o"
	done
}

build_one() {
	./configure \
		--prefix="$PREFIX" \
		--disable-shared \
		--enable-static \
		--disable-doc \
		--disable-programs \
		--disable-encoders \
		--disable-muxers \
		--disable-avdevice \
		--disable-avfilter \
		--disable-doc \
		--disable-symver \
		$(all enable muxer flv mp4 matroska) \
		--cross-prefix="$CROSS_PREFIX" \
		--target-os=linux \
		--arch="${CTARGET%%-*}" \
		--enable-cross-compile \
		--sysroot="$SYSROOT" \
		--extra-cflags="-Os -fpic -fdiagnostics-color=auto $EXTRA_CFLAGS" \
		--extra-ldflags="$EXTRA_LDFLAGS" \
		$EXTRA_CONF "$@"
	[ "$ON_BUILDBOT" ] || make clean
	make -j12
	make install
}

arch() {
	ARCH="$1"
	EXTRA_CFLAGS=
	EXTRA_CONF=
	
	case "$1" in
		arm)
			CTARGET=arm-linux-androideabi
			EXTRA_CFLAGS="-marm"
		;;
		x86)
			CTARGET=i686-linux-android
			EXTRA_CONF="--disable-amd3dnow --disable-amd3dnowext"
		;;
		*)
			echo "Unsupported arch $ARCH"
			exit 1
		;;
	esac

	PREFIX="$WORKSPACE/dist/$ARCH"
	SYSROOT="$NDK/platforms/android-9/arch-$ARCH"
	TOOLCHAIN="$(echo "$NDK"/toolchains/$ARCH*-4.8/prebuilt/linux-x86*)"
	CROSS_PREFIX="$TOOLCHAIN/bin/$CTARGET-"
}


if [ "$ON_BUILDBOT" ] ; then
	arch "${label#android-}"

	cd S
	. "$B_SCRIPTS_D/git/reset"

	build_one
else
	set -e
	for a in arm x86 ; do
		( arch $a && build_one )
	done
fi
