#! /bin/sh

. "$B_SCRIPTS_D/delegate-shell"

[ -z "$PATH_OVERRIDE" ] || PATH="$PATH_OVERRIDE"
rm -rf _lib_

cd S
. "$B_SCRIPTS_D/git/reset"
unset CFLAGS CXXFLAGS
if [ "$BUILD_DEBUG" = 'true' ] ; then
	myconf="--disable-optimizations"
else
	myconf=
fi
is_mingw=
case "${label:=$LABEL}" in
	mingw*)
		is_mingw=1
		myconf="$myconf --disable-pthreads"
		[ -z "$B_CROSS_COMPILE" ] || myconf="$myconf --cross-prefix=$CTARGET- --target-os=mingw32 --arch=${CTARGET%%-*}"
	;;
esac
_enable() {
	local o
	for o ; do
		grep -qw "enable-$o" configure && echo "--enable-$o"
	done
}
./configure \
	--pkg_config=pkg-config \
	--prefix=/. \
	--enable-gpl --enable-nonfree \
	--disable-doc \
	--enable-runtime-cpudetect \
	--enable-dxva2 \
	--enable-zlib --enable-gnutls \
	--enable-libfreetype $(_enable fontconfig libass) \
	$(_enable avresample) \
	--enable-libopus \
	--enable-debug \
	$myconf
[ -z "$is_mingw" ] || sed -i -r -e 's/(HAVE_NANOSLEEP) 1/\1 0/g' config.h

make $M_JOBS V=1
make DESTDIR="$WORKSPACE/_lib_" install
sed -i -r -e 's:^(prefix=)/.:\0:g' ../_lib_/lib/pkgconfig/*.pc

. "$B_SCRIPTS_D/autoconf/run" aggregate
