#! /bin/sh

B_EXTRA_CONF="--without-manual"

. "$B_SCRIPTS_D/autoconf/run" init

. "$B_SCRIPTS_D/patches/apply" libquvi

WANT_AUTOMAKE=1.11 \
. "$B_SCRIPTS_D/autoconf/run" gen build pack aggregate

sed -i \
	-e '/^Libs:/s/$/ -llua -lcurl -lcares -lws2_32 -lwldap32/' \
	-e '/^Cflags:/s/$/ -DCARES_STATICLIB/' \
	../_lib_/lib/pkgconfig/libquvi.pc
