#! /bin/sh

[ -z "$PATH_OVERRIDE" ] || PATH="$PATH_OVERRIDE"

cd S
. "$B_SCRIPTS_D/git/reset"
. "$B_SCRIPTS_D/download/opengl-extension-headers"

. "$B_SCRIPTS_D/patches/apply" mpv

CFLAGS=
CXXFLAGS=
[ "$BUILD_DEBUG" != true ] || CFLAGS="-pipe -O0 -g"

myconf="$myconf --disable-terminfo --disable-termcap --disable-termios --disable-lirc"
sed -i -r -e 's/if opts\[.execute.\] == True/if "execute" in opts and opts["execute"]/' waftools/checks/generic.py
CPPFLAGS="$CPPFLAGS -U__STRICT_ANSI__"

waf configure --prefix=/. \
	--enable-static \
	--enable-static-build \
	--disable-manpage-build \
	--disable-pdf-build \
	$myconf
waf build --verbose

cd build
mv mpv.exe mpv_debug.exe
$CTARGET-strip -o mpv.exe mpv_debug.exe
. "$B_SCRIPTS_D/pack/7z" mpv.exe
