#! /bin/sh

[ -z "$PATH_OVERRIDE" ] || PATH="$PATH_OVERRIDE"

cd S
. "$B_SCRIPTS_D/git/reset"
. "$B_SCRIPTS_D/download/opengl-extension-headers"

sed -i \
	-e 's:BASE_SEARCH_PATH_ENABLE_SAFE_SEARCHMODE:0x00000001:g' \
	audio/out/ao_wasapi0.c
sed -i \
	-e 's:CONFIG_LIBASS:CONFIG_ASS:g' \
	demux/demux.c

unset CFLAGS CXXFLAGS
[ "$BUILD_DEBUG" != true ] || export CFLAGS="-pipe -O0 -g"
myconf=
case "$label" in
	mingw*)
		myconf="$myconf --disable-termcap --disable-termios --disable-lirc --disable-lircc"
	;;
esac

./configure \
	--enable-cross-compile --target=$CTARGET --pkg-config=pkg-config \
	--prefix= \
	--enable-static \
	--disable-manpage \
	--extra-libs-mpv="-L$REF/lib -ldvdcss" \
	$myconf

make $M_JOBS V=1
mv mpv.exe mpv_debug.exe
$CTARGET-strip -o mpv.exe mpv_debug.exe
