#! /bin/sh

. "$B_SCRIPTS_D/toolchain/map" "$@"

if [ "${Configuration:=$CONFIGURATION}" = 'Debug' -o "$BUILD_DEBUG" = 'true' ] ; then
	CFLAGS_OPT="-O0"
	CPPFLAGS_OPT=
else
	CFLAGS_OPT="-O3"
	CPPFLAGS_OPT="-DNDEBUG"
fi

e TMPDIR "$(_pwd)/_tmp_"
rm -rf "$TMPDIR"
mkdir "$TMPDIR"

_pkg_config_sysroot() {
	e PKG_CONFIG_SYSROOT_DIR "$REF"
}

e REF "$(_pwd)/S/_lib_"
e CFLAGS "$CFLAGS_OPT -pipe -g -fno-strict-aliasing"
e CXXFLAGS "$CFLAGS"
e CPPFLAGS "$CPPFLAGS_OPT -I$REF/include$NO_CYGWIN"
e LDFLAGS "-L$REF/lib$NO_CYGWIN"
B_CONF_CROSS_PREFIX=
[ -z "$B_CROSS_COMPILE" ] || B_CONF_CROSS_PREFIX="--host=$CTARGET --build=$CBUILD "
e B_CONF "$B_CONF_CROSS_PREFIX--prefix= --enable-static --disable-shared --disable-nls --disable-i18n"
case "$T" in
	mingw-w32|mingw-w64|*-cygwin)
		_pkg_config_sysroot
	;;
esac

cat <<_EOF_
M_JOBS=-j 8
PKG_CONFIG=pkg-config
PKG_CONFIG_LIBDIR=$REF/lib/pkgconfig
_EOF_
