#! /bin/sh

. "$B_SCRIPTS_D/toolchain/map" "$@"

if [ "${Configuration:=$CONFIGURATION}" == 'Debug' -o "$BUILD_DEBUG" == 'true' ] ; then
	CFLAGS_OPT="-O0"
else
	CFLAGS_OPT="-O3 -DNDEBUG"
fi

e TMPDIR "$(_pwd)/S/_tmp_"
[ -d "$TMPDIR" ] || mkdir "$TMPDIR"

_pkg_config_sysroot() {
	e PKG_CONFIG_SYSROOT_DIR "$REF"
}

e REF "$(_pwd)/S/_lib_"
e CFLAGS "-pipe -g $CFLAGS_OPT"
e CXXFLAGS "$CFLAGS"
e CPPFLAGS "-I$REF/include$NO_CYGWIN"
e LDFLAGS "-L$REF/lib$NO_CYGWIN"
e B_CONF "--host=$CTARGET --build=$CBUILD --prefix= --enable-static --disable-shared --disable-nls --disable-i18n"
case "$T" in
	mingw-w32|mingw-w64|*-cygwin)
		_pkg_config_sysroot
	;;
esac

cat <<_EOF_
CC=$CTARGET-gcc$exe
CXX=$CTARGET-g++$exe
M_JOBS=-j 8
PKG_CONFIG=pkg-config
PKG_CONFIG_LIBDIR=$REF/lib/pkgconfig
_EOF_
