#! /bin/sh

_init() {
	rm -rf _lib_

	cd S
	[ ! -d .git ] || . "$B_SCRIPTS_D/git/reset"
}

_autoreconf() {
	autoreconf -if
}

_configure() {
	./configure $B_CONF $B_EXTRA_CONF
}

_gen() {
	if [ "$B_AUTORECONF" ] || ( [ ! -e configure ] && [ -e configure.ac -o -e configure.in ] ) ; then
		touch README INSTALL
		_autoreconf
	fi
	_configure
}

_build() {
	make $M_JOBS $B_MAKE_OPTS $B_EXTRA_MAKE_OPTS
}

_pack() {
	make DESTDIR="$WORKSPACE/_lib_" install
}

_aggregate() {
	rsync --remove-source-files _lib_/ ../_lib_/ -av
}

_all() {
	_init
	_gen
	_build
	_pack
}

[ $# -gt 0 ] || set -- all

for a ; do
	_$a
done
