#! /bin/sh

T="${label:-"${LABEL:-"$1"}"}"

if [ -z "$T" ] ; then
	echo '$label and $1 is not set' 1>&2
	exit 1
fi

_cmake() {
	echo "CMAKE_EXECUTABLE=/usr/local/bin/cmake-$T"
}

_gmake() {
	echo "CMAKE_BUILDER_OPTIONS=-j8"
}

echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-$Configuration}"

case "$T" in
	mingw*)
		_cmake
		_gmake
	;;
	qt5|clang)
		_cmake
		_gmake
	;;
	vs2012)
		G="Visual Studio 11"
		case "$TARGET" in
			x86) : ;;
			x64)
				G="$G Win64"
			;;
			*)
				echo "Unknown target $TARGET" 1>&2
				exit 1
			;;
		esac
		echo "CMAKE_GENERATOR=$G"
		# CMake does not use MSBuild, it uses devenv instead.
		#echo "CMAKE_BUILDER_OPTIONS=/m"
	;;
	borland)
		echo "CMAKE_GENERATOR=Borland Makefiles"
	;;
esac
