#! /bin/sh

T="${TARGET:-"$1"}"

if [ -z "$T" ] ; then
	echo '$TARGET and $1 is not set' 1>&2
	exit 1
fi

case "$T" in
	x86)
		echo 'CMAKE_GENERATOR=Visual Studio 11'
	;;
	x64)
		echo 'CMAKE_GENERATOR=Visual Studio 11 Win64'
	;;
	*)
		echo "Unknown target $T" 1>&2
		exit 1
	;;
esac
