#! /bin/sh

T="${label:="${LABEL:="$1"}"}"

if [ -z "$T" ] ; then
	echo '$label and $1 is not set' 1>&2
	exit 1
fi

e() {
	eval "$1='$2'"
	echo "$1=$2"
}

B_SYSTEM_NAME="`uname -s`"
case "$T" in
	mingw-w32)
		e CTARGET i686-w64-mingw32

		if [ "$OPT_TOOLCHAIN" ] ; then
			e PATH_OVERRIDE "/opt/i686-w64-mingw32/gcc-bin:/opt/i686-w64-mingw32/bin:`echo $PATH | sed -r 's#[^:]+i686-w64-mingw32[^:]+##g'`"
			e PATH "$PATH_OVERRIDE"
			e CRT_GLOB "/opt/$CTARGET/$CTARGET/lib/CRT_glob.o"
			e SYSROOT "/opt/$CTARGET/$CTARGET"
		else
			e CRT_GLOB "/usr/$CTARGET/lib/CRT_glob.o"
			e SYSROOT "/usr/$CTARGET"
		fi
	;;
	mingw-w64)
		e CTARGET x86_64-w64-mingw32
		e CRT_GLOB "/usr/$CTARGET/$CTARGET/lib/CRT_glob.o"
		e SYSROOT "/usr/$CTARGET/$CTARGET"
	;;
esac

exe=
case "$B_SYSTEM_NAME" in
	MINGW*)
		CBUILD="$CTARGET"
		exe=.exe
	;;
	CYGWIN*)
		CBUILD="$CTARGET"
		NO_CYGWIN=" -mno-cygwin"
	;;
	*)
		CBUILD="`gcc -dumpmachine`"
	;;
esac
