#! /bin/sh

T="${label:="${LABEL:="$1"}"}"

if [ -z "$T" ] ; then
	echo '$label and $1 is not set' 1>&2
	exit 1
fi

e() {
	eval "$1='$2'"
	echo "$1=$2"
}

_msys() {
	PATH_WINDOWS=":/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem"
	PATH_BASE="/usr/local/bin:/bin$PATH_WINDOWS:/e/software/_dev_/nasm:/e/software/_dev_/posix:/e/software/_util_/GnuWin32/root/bin"
	PATH="$PATH_BASE"
}

B_SYSTEM_NAME="`uname -s`"
case "$T" in
	mingw-w32)
		e R_DEFAULT "$T"
		e R_MSYS mingw-w32-msys

		e B_CROSS_COMPILE 1
		e CTARGET i686-w64-mingw32

		if [ "$OPT_TOOLCHAIN" ] ; then
			e PATH_OVERRIDE "/opt/i686-w64-mingw32/gcc-bin:/opt/i686-w64-mingw32/bin:`echo $PATH | sed -r 's#[^:]+i686-w64-mingw32[^:]+##g'`"
			e PATH "$PATH_OVERRIDE"
			e CRT_GLOB "/opt/$CTARGET/$CTARGET/lib/CRT_glob.o"
			e SYSROOT "/opt/$CTARGET/$CTARGET"
		else
			e CRT_GLOB "/usr/$CTARGET/lib/CRT_glob.o"
			e SYSROOT "/usr/$CTARGET"
		fi
	;;
	mingw-w64)
		e R_DEFAULT "$T"
		e R_MSYS "$T"

		e B_CROSS_COMPILE 1
		e CTARGET x86_64-w64-mingw32
		e CRT_GLOB "/usr/$CTARGET/$CTARGET/lib/CRT_glob.o"
		e SYSROOT "/usr/$CTARGET/$CTARGET"
	;;
	mingw-w32-msys)
		_msys
		e R_DEFAULT mingw-w32
		e R_MSYS "$T"

		e CTARGET i686-w64-mingw32
		tc_path="`echo /c/Qt/Qt5*/Tools/MinGW`"
		e SYSROOT "$tc_path/$CTARGET"
		e PATH_OVERRIDE "$tc_path/bin:$PATH"
		e PATH "$PATH_OVERRIDE"
		e CRT_GLOB "$SYSROOT/lib/CRT_glob.o"
	;;
esac

exe=
_pwd() {
	pwd "$@"
}
case "$B_SYSTEM_NAME" in
	MINGW*)
		CBUILD="$CTARGET"
		exe=.exe

		_pwd() {
			pwd -W "$@"
		}
	;;
	CYGWIN*)
		CBUILD="$CTARGET"
		NO_CYGWIN=" -mno-cygwin"
	;;
	*)
		CBUILD="`gcc -dumpmachine`"
	;;
esac
